//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVTower.DBEditorGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SERVER=localhost;DATABASE=tvtower_new;UID=TVTowerUser;PASSWORD=123")]
        public string DBConnection {
            get {
                return ((string)(this["DBConnection"]));
            }
            set {
                this["DBConnection"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Haftungsausschluss!

Bitte bestätigen Sie durch das Aktivieren der Schaltfläche ""Akzeptieren"", dass Sie alle Einschränkungen bezüglich des Schutz des Namensrechts (§ 12 BGB) als auch des Titelschutzes (§§ 5, 15 MarkenG) bei der Bearbeitung von Film- und Personendaten beachten, sofern Sie nicht alle erforderlichen Berechtigungen besitzen oder in Ihrem Wohnsitz keine Notwendigkeit besteht, solche Rechte einzuholen. Die Autoren dieses Software-Programmes übernehmen keinerlei Haftung.")]
        public string Disclaimer {
            get {
                return ((string)(this["Disclaimer"]));
            }
        }
    }
}
